version: '2.3'

services:
  autopilot_predict:
    build:
      context: .
      dockerfile: "Dockerfile"
    user: $DOCKER_USER:$DOCKER_GROUP
    cpus: 32
    image: "merengelke/autopilot_predict_tf"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=1,2,3,4
      - FHIR_USER=$FHIR_USER
      - FHIR_PASSWORD=$FHIR_PASSWORD
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_GROUP=$DOCKER_GROUP
      - SEARCH_URL=$SEARCH_URL
      - BASIC_AUTH=$BASIC_AUTH
      - REFRESH_AUTH=$REFRESH_AUTH
      - DICOM_WEB_URL_GEPACS=$DICOM_WEB_URL_GEPACS
      - DICOM_WEB_URL_EA=$DICOM_WEB_URL_EA
      - DICOM_WEB_URL_CHILI=$DICOM_WEB_URL_CHILI
      - WANDB_API_KEY=$WANDB_API_KEY
      - WANDB_DIR=/autopilot/wandb
      - WANDB_CACHE_DIR=/autopilot/wandb
      - WANDB_CONFIG_DIR=/autopilot/wandb
      - WANDB_DATA_DIR=/autopilot/wandb
    volumes:
      - ./app:/autopilot/app
      - ./wandb:/autopilot/wandb
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /local/work/merengelke/autopilot:/data
    working_dir: /autopilot
    shm_size: '1gb'

networks:
  default:
    name: "merengelke"