method: bayes
metric:
  goal: maximize
  name: best_val_prc
parameters:
  batch_size:
    values: [256, 512, 1024]
  clinic_filter:
    value: 'clinic_filter'
  dataset_name:
    value: '0.3.1'
  in_lstm:
    values: [64, 128]
  out_lstm:
    values: [64, 128, 256]
  learning_rate:
    value: 0.001
  norm_type:
    values: ['LayerNorm' , 'BatchNorm']
  apply_weight_balancing:
    values: [ True , False ]
  loss_function:
    values: ['Adam', 'AdamW']
  dense:
    values: [128, 256, 512, 1024]
  use_sam:
    value: True
early_terminate:
  type: hyperband
  max_iter: 160
  s: 3
  eta: 2

  #In the cases where I have max_iter=150, eta=3, and s=4, the early stopping will occur based on the epochs [150/3, 150/9, 150/27, 150/81]
program: -mapp.run
project: autopilot_heart_thorax