wandb_version: 1

booster:
  desc: null
  value: dart
gamma:
  desc: null
  value: 3.055695688229386e-08
grow_policy:
  desc: null
  value: lossguide
learning_rate:
  desc: null
  value: 0.00372954489429452
max_depth:
  desc: null
  value: 20
reg_alpha:
  desc: null
  value: 0.05145298907359536
reg_lambda:
  desc: null
  value: 5.553458253232278e-05
sampling_method:
  desc: null
  value: gradient_based
is_live_prediction:
  desc: null
  value: false
reload_cache:
  desc: null
  value: false
time_delta:
  desc: null
  value: 10
start_datetime:
  desc: null
  value: 01-01-2017
end_datetime:
  desc: null
  value: 01-01-2022
read_from_fhir_cache:
  desc: null
  value: false
bundle_cache_folder_path:
  desc: null
  value: /nvme/shared/autopilot/training/cache
folders_to_clear:
  desc: null
  value:
  - /nvme/shared/autopilot/training
  - /nvme/shared/autopilot/training_filtered
  - /nvme/shared/autopilot/training_tfds/autopilot_dataset
  - /nvme/shared/autopilot/training_tfds/downloads
bdp_path:
  desc: null
  value: /nvme/shared/autopilot/training/bdp.ftr
bdp_path_filtered:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/bdp.ftr
bdp_params:
  desc: null
  value:
    shipProductCode: TKZ,TKP
    _count: 1000
    _sort: -shipStorageEnd
    _include: BiologicallyDerivedProduct:request
obs_path:
  desc: null
  value: /nvme/shared/autopilot/training/obs.ftr
obs_raw:
  desc: null
  value: /nvme/shared/autopilot/training/obs_raw.ftr
obs_path_filtered:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/obs.ftr
obs_params:
  desc: null
  value:
    code: zTHRA
    _count: 500
    _sort: -date
    _include: Observation:based-on
base_for_patient:
  desc: null
  value: /nvme/shared/autopilot/training/obs.ftr
patient_path:
  desc: null
  value: /nvme/shared/autopilot/training/patient.ftr
patient_path_filtered:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/patient.ftr
patient_params:
  desc: null
  value:
    _count: 1000
    _sort: -birthdate
patient_constraints:
  desc: null
  value:
    _id: patient_id
base_for_procedure:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/patient.ftr
procedure_path:
  desc: null
  value: /nvme/shared/autopilot/training/procedure.ftr
procedure_path_filtered:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/procedure.ftr
procedure_params:
  desc: null
  value:
    _count: 1000
    _sort: -date
procedure_constraints:
  desc: null
  value:
    subject: patient_id
base_for_procedure_op_plan:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/patient.ftr
procedure_op_plan_path:
  desc: null
  value: /nvme/shared/autopilot/training/procedure_op_plan.ftr
procedure_op_plan_path_filtered:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/procedure_op_plan.ftr
procedure_op_plan_constraints:
  desc: null
  value:
    subject: patient_id
procedure_params_op_plan:
  desc: null
  value:
    _count: 1000
    _sort: -date
base_for_encounter:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/patient.ftr
encounter_path:
  desc: null
  value: /home/merengelke/autopilot_ml/data_preprocessing/raw_data/encounter.ftr
encounter_path_filtered:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/encounter_legacy.ftr
encounter_params:
  desc: null
  value:
    _count: 1000
    _sort: -date
encounter_constraints:
  desc: null
  value:
    subject: patient_id
base_for_condition:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/patient.ftr
condition_path:
  desc: null
  value: /nvme/shared/autopilot/training/condition.ftr
condition_path_filtered:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/condition.ftr
condition_params:
  desc: null
  value:
    _count: 1000
    _sort: -recorded-date
condition_constraints:
  desc: null
  value:
    subject: patient_id
base_for_medication:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/patient.ftr
medication_path_raw:
  desc: null
  value: /nvme/shared/autopilot/training/medication_raw.ftr
medication_path:
  desc: null
  value: /nvme/shared/autopilot/training/medication.ftr
medication_merged_path:
  desc: null
  value: /nvme/shared/autopilot/training/medication_merged.ftr
medication_merged_path_filtered:
  desc: null
  value: /nvme/shared/autopilot/training_filtered/medication.ftr
medication_params:
  desc: null
  value:
    _count: 1000
    _sort: _lastUpdated
medication_req_params:
  desc: null
  value:
    _count: 1000
    _sort: _lastUpdated
medication_admin_params:
  desc: null
  value:
    _count: 1000
    _sort: _lastUpdated
medication_constraints:
  desc: null
  value:
    subject: patient_id
preprocessed_by_encounter_path:
  desc: null
  value: /nvme/shared/autopilot/training_training_data/preprocessed_by_encounter.pkl
preprocessed_windows_path:
  desc: null
  value: /nvme/shared/autopilot/training_training_data/windows.pkl
scalars_path:
  desc: null
  value: app/config/scalers.pkl
batch_size:
  desc: null
  value: 512
dataset_name:
  desc: null
  value: 0.1.3
epochs:
  desc: null
  value: 100
dataset_dir:
  desc: null
  value: /nvme/shared/autopilot/training_tfds
wb_project_name:
  desc: null
  value: autopilot_hema_onco
weight_decay_score:
  desc: null
  value: 0
in_lstm:
  desc: null
  value: 128
out_lstm:
  desc: null
  value: 128
prefetch:
  desc: null
  value: true
train_size:
  desc: null
  value: 0.8
shuffle_files:
  desc: null
  value: true
as_supervised:
  desc: null
  value: false
dense:
  desc: null
  value: 256
norm_type:
  desc: null
  value: LayerNorm
apply_weight_balancing:
  desc: null
  value: 'False'
loss_function:
  desc: null
  value: AdamW
use_sam:
  desc: null
  value: false
clinic_filter:
  desc: null
  value: none
input_dim_station_embedding:
  desc: null
  value: 291
age_gender_metas:
  desc: null
  value: /nvme/shared/autopilot/training_publish/age_gender_metas.pkl
image:
  desc: null
  value: /home/merengelke/autopilot_clean/img_cohort.jpeg
image_test_results:
  desc: null
  value: /home/merengelke/autopilot_clean/test_results.eps
procedure_counts:
  desc: null
  value: /nvme/shared/autopilot/training_publish/pro_counts.pkl
medication_counts:
  desc: null
  value: /nvme/shared/autopilot/training_publish/med_counts.pkl
condition_counts:
  desc: null
  value: /nvme/shared/autopilot/training_publish/cond_counts.pkl
model_path:
  desc: null
  value: app/config/model_
root_dir:
  desc: null
  value: /nvme/shared/autopilot/
explanation_dir:
  desc: null
  value: /nvme/shared/autopilot/xai_lstm
classic_ml_dir:
  desc: null
  value: /nvme/shared/autopilot/classic_ml/none
model_type:
  desc: null
  value: rf
command:
  desc: null
  value: ml
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.4
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687984490.473168
    t:
      1:
      - 2
      - 3
      - 5
      - 6
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.9.12
      5: 0.15.4
      8:
      - 5
    visualize:
      train_confusion_matrix:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/confusion_matrix/v1
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          stringSettings:
            title: train
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: train_confusion_matrix_table
                fields: []
      val_confusion_matrix:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/confusion_matrix/v1
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          stringSettings:
            title: val
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: val_confusion_matrix_table
                fields: []
      test_confusion_matrix:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/confusion_matrix/v1
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          stringSettings:
            title: test
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: test_confusion_matrix_table
                fields: []
